site_name: Predator
site_url: https://predator.dev
repo_url: https://github.com/Zooz/predator
edit_uri: https://github.com/Zooz/predator/blob/master/docs/devguide/docs/
site_description: Distributed open source performance testing platform for APIs
site_author: ZOOZ
google_analytics: ['UA-40865650-4', 'auto']

nav:
  - About: index.md
  - Installation: installation.md
  - My First Test: myfirsttest.md
  - Advanced Test Setup: tests.md
  - Functional Tests and Assertions: functionalandassertions.md
  - Processor Creation: processors.md
  - Benchmarks: benchmarks.md
  - Webhooks: webhooks.md
  - Streaming Platforms: streaming.md
  - Schedules and Reports: schedulesandreports.md
  - Plugins: plugins.md
  - Configuration: configuration.md
  - Runner's Performance: performance.md
  - Integrating Chaos Mesh with Predator: chaosmesh.md
  - FAQ: faq.md
  - Contributing: contributing.md
  - API Reference: apireference.md

theme:
   name: material
   logo: logo.png

use_directory_urls: False

markdown_extensions:
   - codehilite:
       css_class: codehilite
   - pymdownx.superfences:
   - pymdownx.details:
   - admonition
   - sane_lists
   - fenced_code
   - toc:
       permalink: '#'

extra:
    version: 1.0
    logo: favicon.png
